<a href="https://colab.research.google.com/github/pandit-barkate/MyFirstRepos/blob/main/Multi_Class_Classification_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#pip install seaborn

In [ ]:
import pandas as pd

import seaborn as sns # to get the dataset for multi class classification

In [ ]:
data = sns.load_dataset('iris')

In [ ]:
data

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica


In [ ]:
data['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [ ]:
# divide data in X and y
X = data.drop(['species'],axis=1)

In [ ]:
X

,sepal_length,sepal_width,petal_length,petal_width
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [ ]:
y = data[['species']]

In [ ]:
y

,species
0,setosa
1,setosa
2,setosa
3,setosa
4,setosa
...,...
145,virginica
146,virginica
147,virginica
148,virginica


In [ ]:
# initialize one hot encoder for miltucalss equal number of class
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=False) # values in the diagonal is 1 in matrix


In [ ]:
y_transform = encoder.fit_transform(y)  # expect two dimesion so add [[]] for y

In [ ]:
y_transform

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
# scaling feature in DL
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_transform = scaler.fit_transform(X)

In [ ]:
# Define ANN arcitecture
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense # for mlp alsways desn

# initialize model
model = Sequential()

# 1st layer => i/p layer
model.add(Dense(units=4,activation='relu')) # nuron = number of feature

#2nd hiden layer
model.add(Dense(units=8,activation='relu'))  # souble of first

#3rd layer
model.add(Dense(units=16,activation='relu'))

# final layer - Op/p layer
model.add(Dense(units=3,activation='softmax'))  # nuron = number of classes

In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# model.compile

model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
# loss for multi class categorical_crossentropy
# loss for regression is mse


In [ ]:
# split data in train test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_transform,y_transform,test_size=0.2)

In [ ]:
# training model
model.fit(X_train,y_train,epochs=100)  # model is trained 100 times on same data

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9881 - loss: 0.0308
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9912 - loss: 0.0238 
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9767 - loss: 0.0434 
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9819 - loss: 0.0425 
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9881 - loss: 0.0327 
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9798 - loss: 0.0400 
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9819 - loss: 0.0431 
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9881 - loss: 0.0329 
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9933 - loss: 0.0285 
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9881 - loss: 0.0356 
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9912 - loss: 0.0240 
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9767 - loss

In [ ]:
#  model Eval
import numpy as np
y_pred = model.predict(X_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step


In [ ]:
y_pred

array([[9.2156727e-09, 7.8057417e-07, 9.9999917e-01],
       [1.8068151e-06, 9.9983770e-01, 1.6049074e-04],
       [5.4242050e-06, 9.3913925e-01, 6.0855407e-02],
       [6.6063257e-07, 3.2588679e-05, 9.9996680e-01],
       [9.9999917e-01, 7.8344607e-07, 7.4642896e-09],
       [5.2759633e-04, 5.2869970e-01, 4.7077280e-01],
       [9.9999869e-01, 1.3466143e-06, 1.3679938e-08],
       [3.0514600e-06, 2.1284794e-04, 9.9978417e-01],
       [6.6792921e-08, 1.0820263e-05, 9.9998915e-01],
       [9.9999917e-01, 7.7712696e-07, 8.1047897e-09],
       [5.1663988e-05, 1.4169759e-03, 9.9853134e-01],
       [9.9999917e-01, 8.0928572e-07, 6.1370065e-09],
       [4.2023193e-04, 3.6805427e-01, 6.3152552e-01],
       [9.9999881e-01, 1.2261369e-06, 7.5660287e-09],
       [1.8508220e-07, 1.1826748e-05, 9.9998796e-01],
       [1.4016179e-05, 1.1778171e-03, 9.9880809e-01],
       [1.9667892e-09, 1.0000000e+00, 5.6367537e-09],
       [9.9999666e-01, 3.3727679e-06, 2.8252243e-08],
       [3.4769805e-06, 2.194

In [ ]:
# above y_pred is the probability of all 3 classes
# convert these probability to valeus
import numpy as np
y_pred_Argmax = np.argmax(y_pred,axis=1)

# argmax() finds higest value and return the index value and the valur itself

In [ ]:
y_pred_Argmax

array([2, 1, 1, 2, 0, 1, 0, 2, 2, 0, 2, 0, 2, 0, 2, 2, 1, 0, 2, 0, 0, 0,
       0, 0, 2, 2, 2, 0, 0, 1])

In [ ]:
y_test

array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [ ]:
# so convert this y_test to argmax

y_test_argmax = np.argmax(y_test,axis=1)

In [ ]:
y_test_argmax

array([2, 1, 1, 2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 0, 2, 2, 1, 0, 2, 0, 0, 0,
       0, 0, 2, 2, 2, 0, 0, 1])

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test_argmax,y_pred_Argmax))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.80      1.00      0.89         4
           2       1.00      0.92      0.96        13

    accuracy                           0.97        30
   macro avg       0.93      0.97      0.95        30
weighted avg       0.97      0.97      0.97        30

